style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/erajayatech/go-opentelemetry
options:
  commits:
    filters:
      Type:
        - feat
        - bugfix
        - hotfix
        - refactor
        - test
        - misc
  commit_groups:
    title_maps:
      feat: Features
      bugfix: Fixes
      hotfix: Fixes
      refactor: Code Improvements
      test: Test Improvements
      misc: Other Improvements
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE